### ISSUE TITLE
scan a barcode

### ISSUE THREAD

**Issue by bachtiar-madya-p** [sampurnoaji/Android-QRCodeScanner#3]
![112233445566](https://user-images.githubusercontent.com/15031909/64123850-a57f0480-cdcf-11e9-896e-016eb8b1a0cb.png)

**Comment by sampurnoaji** [comment]
Done

**Comment by bachtiar-madya-p** [comment]
i dont think so, scan the attached barcode and send the asset code to server, then retrieve the response details
